---
title: "Movies on IMDB & Rotten Tomatoes"
author: ""
date: "04.17.19"
runtime: shiny 
output: html_document
---

```{r include = FALSE}
library(tidyverse)
library(shiny)
library(tools)
```

The data were scraped from IMDB and Rotten Tomatoes and represent a random sample of 651 movies released in the United States between 1970 and 2014.

```{r load-data}
load("movies.Rdata")
```

The variables in the data are as follows: 

```{r variables}
names(movies)
``` 


Below is a shiny app you can use to explore some of the variables and the relationships between them.

```{r shiny-app, echo = F}

# Define UI ---------------------------------------------------------
ui <- fluidPage(
  
  # App title
  titlePanel("Movie browser"),
  
  # Sidebar layout with a input and output definitions
  sidebarLayout(
    
    # Inputs: Select variables to plot
    sidebarPanel(
      
      # Subtitle
      h4("Sample"),
      
      # Set sample size
      numericInput(inputId = "sample_size", 
                   label = "Enter a sample size between 1 and 651:",
                   min = 1, max = nrow(movies), 
                   value = 30),
      
      # Take random sample
      actionButton(inputId = "sample_button",
                   label = "Take random sample"),
      
      # Write random sample to csv
      actionButton(inputId = "write_csv",
                   label = "Write CSV"),
      
      #Visual separation
      br(), hr(),
      
      #Subtitle
      h4("Plot"),
        
      
      # Select variable for y-axis
      selectInput(inputId = "y", 
                  label = "Y-axis:",
                  choices = c("IMDB rating" = "imdb_rating", 
                              "IMDB number of votes" = "imdb_num_votes", 
                              "Critics Score" = "critics_score", 
                              "Audience Score" = "audience_score", 
                              "Runtime" = "runtime"), 
                  selected = "audience_score"),
      
      # Select variable for x-axis
      selectInput(inputId = "x", 
                  label = "X-axis:",
                  choices = c("IMDB rating" = "imdb_rating", 
                              "IMDB number of votes" = "imdb_num_votes", 
                              "Critics Score" = "critics_score", 
                              "Audience Score" = "audience_score", 
                              "Runtime" = "runtime"), 
                  selected = "critics_score"),
      
      # Select variable for color
      selectInput(inputId = "z", 
                  label = "Color by:",
                  choices = c("Title Type" = "title_type", 
                              "Genre" = "genre", 
                              "MPAA Rating" = "mpaa_rating", 
                              "Critics Rating" = "critics_rating", 
                              "Audience Rating" = "audience_rating"),
                  selected = "mpaa_rating"),
      
      # Set alpha level
      sliderInput(inputId = "alpha", 
                  label = "Alpha:", 
                  min = 0, max = 1, 
                  value = 0.5),
      
      # Show data table
      checkboxInput(inputId = "show_data",
                    label = "Show data table",
                    value = TRUE)

    ),
    
    # Output:
    mainPanel(
      
      # Show scatterplot
      plotOutput(outputId = "scatterplot"),
      br(),        # a little bit of visual separation
      
      # Print number of obs plotted
      uiOutput(outputId = "n"),
      br(), br(),    # a little bit of visual separation

      # Show data table
      DT::dataTableOutput(outputId = "moviestable")
    )
  )
)

# Define server function --------------------------------------------
server <- function(input, output) {
  
  # Create a subset of data of selected size
  movies_sample <- eventReactive(
    # when button is clicked
    input$sample_button, {
      
      # take a sample
      movies %>% sample_n(input$sample_size)
    }, 
     ignoreNULL = FALSE
  )
  
  # Write random sample to csv
  observeEvent(
    
    # when button is clicked
    input$write_csv, {
      
      # clean up text for now
      now <- Sys.time() %>%
        str_replace_all("\\:", "-") %>%
        str_replace(" ", "_")
      
      # create a filename with movie_sample and timestamp
      filename <- paste0("movies_sample", now, ".csv")
      
      #write csv
      write_csv(movies_sample(), path = filename)
    }
  )
  
  # Create scatterplot object the plotOutput function is expecting
  output$scatterplot <- renderPlot({
    ggplot(data = movies_sample(), aes_string(x = input$x, y = input$y,
                                              color = input$z)) +
      geom_point(alpha = input$alpha) +
      labs(x = toTitleCase(str_replace_all(input$x, "_", " ")),
           y = toTitleCase(str_replace_all(input$y, "_", " ")),
           color = toTitleCase(str_replace_all(input$z, "_", " ")))
  })
  
  
  # Print data table if checked
  output$moviestable <- DT::renderDataTable(
    if(input$show_data){
      DT::datatable(data = movies_sample()[, 1:7], 
                    options = list(pageLength = 10), 
                    rownames = FALSE)
    }
  )
}

# Create the Shiny app object ---------------------------------------
shinyApp(ui, server, options = list(height= 1000))
```
